import crypto from "node:crypto";
import path from "node:path";
import { normalizePasswordHash } from "./password.mjs";

function integer(env, name, fallback, { min = 1, max = Number.MAX_SAFE_INTEGER } = {}) {
  const value = Number.parseInt(env[name] || String(fallback), 10);
  if (!Number.isInteger(value) || value < min || value > max) {
    throw new Error(`${name} must be an integer between ${min} and ${max}`);
  }
  return value;
}

function boolean(value, fallback = false) {
  if (value === undefined || value === "") return fallback;
  if (["1", "true", "yes"].includes(String(value).toLowerCase())) return true;
  if (["0", "false", "no"].includes(String(value).toLowerCase())) return false;
  throw new Error("Expected a boolean environment value");
}

function requiredProduction(env, names) {
  const missing = names.filter((name) => !String(env[name] || "").trim());
  if (missing.length) throw new Error(`Missing required production environment variables: ${missing.join(", ")}`);
}

export function loadConfig(env = process.env, root = process.cwd()) {
  const production = env.NODE_ENV === "production";
  const adminPasswordHash = normalizePasswordHash(env.ADMIN_PASSWORD_HASH);
  const appOrigin = new URL(env.APP_ORIGIN || "http://localhost:3000");
  if (!["http:", "https:"].includes(appOrigin.protocol)) throw new Error("APP_ORIGIN must use http or https");
  if (production && appOrigin.protocol !== "https:") throw new Error("APP_ORIGIN must use HTTPS in production");

  const openAIBaseUrl = new URL(env.OPENAI_API_BASE_URL || "https://api.openai.com/v1");
  if (production && (openAIBaseUrl.protocol !== "https:" || openAIBaseUrl.hostname !== "api.openai.com")) {
    throw new Error("Production OPENAI_API_BASE_URL must be https://api.openai.com/v1");
  }

  if (production) {
    requiredProduction(env, [
      "APP_ORIGIN",
      "ADMIN_USERNAME",
      "ADMIN_PASSWORD_HASH",
      "SESSION_SECRET",
      "OPENAI_API_KEY",
    ]);
    const hasDatabaseUrl = Boolean(String(env.DATABASE_URL || "").trim());
    const databaseParts = ["DB_HOST", "DB_NAME", "DB_USER", "DB_PASSWORD"];
    const hasDatabaseParts = databaseParts.every((name) => Boolean(String(env[name] || "").trim()));
    if (!hasDatabaseUrl && !hasDatabaseParts) {
      throw new Error(`Configure DATABASE_URL or all of: ${databaseParts.join(", ")}`);
    }
    if (String(env.SESSION_SECRET).length < 32) throw new Error("SESSION_SECRET must contain at least 32 characters");
    if (!adminPasswordHash.startsWith("scrypt$")) {
      throw new Error("ADMIN_PASSWORD_HASH must be generated by npm run auth:hash-password");
    }
  }
  if (env.ADMIN_TOTP_SECRET && !/^[A-Z2-7\s=-]{16,}$/i.test(env.ADMIN_TOTP_SECRET)) {
    throw new Error("ADMIN_TOTP_SECRET must be a valid base32 secret");
  }

  const dataDir = path.resolve(root, env.WARDROBE_DATA_DIR || "data");
  const storageDriver = env.STORAGE_DRIVER || "local";
  const localStorageDir = path.resolve(root, env.LOCAL_STORAGE_DIR || path.join(dataDir, "private"));
  if (!["local", "s3"].includes(storageDriver)) throw new Error("STORAGE_DRIVER must be local or s3");
  if (production && storageDriver === "local") {
    if (!boolean(env.ALLOW_LOCAL_PRODUCTION_STORAGE)) {
      throw new Error("Production local storage requires explicit ALLOW_LOCAL_PRODUCTION_STORAGE=true after persistence is verified");
    }
    requiredProduction(env, ["LOCAL_STORAGE_DIR"]);
    if (localStorageDir === path.resolve(root) || localStorageDir.startsWith(`${path.resolve(root)}${path.sep}`)) {
      throw new Error("Production LOCAL_STORAGE_DIR must be outside the deployed application directory so a redeploy cannot overwrite it");
    }
  }
  if (storageDriver === "s3") {
    requiredProduction(env, ["S3_REGION", "S3_BUCKET", "S3_ACCESS_KEY_ID", "S3_SECRET_ACCESS_KEY"]);
  }

  return Object.freeze({
    root,
    production,
    port: integer(env, "PORT", 3000, { max: 65535 }),
    appOrigin,
    trustProxy: production ? integer(env, "TRUST_PROXY", 1, { min: 0, max: 10 }) : false,
    adminUsername: env.ADMIN_USERNAME || "noa",
    adminPasswordHash,
    adminTotpSecret: String(env.ADMIN_TOTP_SECRET || "").replace(/[\s=-]/g, "").toUpperCase(),
    sessionSecret: env.SESSION_SECRET || crypto.randomBytes(48).toString("base64url"),
    sessionCookieName: production ? "__Host-wardrobe.sid" : "wardrobe.sid",
    sessionTtlMs: integer(env, "SESSION_TTL_HOURS", 12, { max: 168 }) * 60 * 60 * 1000,
    databaseUrl: env.DATABASE_URL || "",
    database: env.DATABASE_URL || (env.DB_HOST && env.DB_NAME && env.DB_USER && env.DB_PASSWORD ? {
      host: env.DB_HOST,
      port: integer(env, "DB_PORT", 3306, { max: 65535 }),
      database: env.DB_NAME,
      user: env.DB_USER,
      password: env.DB_PASSWORD,
      waitForConnections: true,
      connectionLimit: integer(env, "DB_CONNECTION_LIMIT", 5, { max: 20 }),
      charset: "utf8mb4",
    } : null),
    openAIKey: env.OPENAI_API_KEY || "",
    openAIBaseUrl: openAIBaseUrl.toString().replace(/\/$/, ""),
    openAIImageModel: env.OPENAI_IMAGE_MODEL || "gpt-image-2",
    openAIImageQuality: env.OPENAI_IMAGE_QUALITY || "medium",
    maxConcurrentOpenAIJobs: integer(env, "MAX_CONCURRENT_OPENAI_JOBS", 1, { max: 4 }),
    dailyImageLimit: integer(env, "DAILY_IMAGE_GENERATION_LIMIT", 0, { min: 0, max: 100_000 }),
    openAITimeoutMs: integer(env, "OPENAI_TIMEOUT_MS", 150_000, { min: 5_000, max: 300_000 }),
    maxUploadBytes: integer(env, "MAX_UPLOAD_MB", 10, { max: 50 }) * 1024 * 1024,
    maxImagePixels: integer(env, "MAX_IMAGE_PIXELS", 40_000_000, { max: 100_000_000 }),
    dataDir,
    modelReference: path.resolve(root, env.WARDROBE_MODEL_REFERENCE || path.join(dataDir, "private", "model-reference.png")),
    storageDriver,
    localStorageDir,
    s3: {
      endpoint: env.S3_ENDPOINT || undefined,
      region: env.S3_REGION || "",
      bucket: env.S3_BUCKET || "",
      accessKeyId: env.S3_ACCESS_KEY_ID || "",
      secretAccessKey: env.S3_SECRET_ACCESS_KEY || "",
      forcePathStyle: boolean(env.S3_FORCE_PATH_STYLE, false),
    },
  });
}
